window.NetBuilderLevelFactories = window.NetBuilderLevelFactories || {};
window.NetBuilderLevelFactories.level5 = ({ validateSchool, schoolPairs }) => ({
  title: "Rete scolastica",
  difficulty: 60,
  available: ["pc", "switch", "server", "firewall", "router", "internet"],
  objective: [
    "Costruisci una rete scolastica gerarchica (aule -> switch centrale -> perimetro).",
    "",
    "Requisiti:",
    "1) Crea 4 switch totali:",
    "- 1 switch centrale",
    "- 3 switch AULA collegati allo switch centrale",
    "",
    "2) Collega i client:",
    "- almeno 2 PC per ogni switch aula (quindi almeno 6 PC totali)",
    "",
    "3) Collega servizi e uscita:",
    "- server collegato allo switch centrale",
    "- switch centrale -> firewall -> router -> Internet",
    "",
    "La prova finale testa PC -> server e PC -> Internet.",
  ].join("\n"),
  checks: [
    "Almeno 6 PC",
    "4 switch totali: 1 switch centrale + 3 aule collegate allo switch centrale",
    "Ogni switch aula ha almeno 2 PC",
    "Server collegato allo switch centrale",
    "Uscita completa: switch centrale -> firewall -> router -> Internet",
  ],
  hint: "Procedi a blocchi: prima lo switch centrale e gli switch aula, poi PC, infine server e uscita WAN.",
  info: "Nella rete gerarchica scolastica il traffico locale converge sullo switch centrale. Da li passa al server interno o esce verso WAN tramite firewall e router.",
  validate: validateSchool,
  pairs: () => schoolPairs(),
});
