window.NetBuilderLevelFactories = window.NetBuilderLevelFactories || {};
window.NetBuilderLevelFactories.level5 = ({ validateSchool, schoolPairs }) => ({
  title: "Rete scolastica",
  difficulty: 60,
  available: ["pc", "switch", "server", "firewall", "router", "internet"],
  objective: [
    "Costruisci una rete scolastica a 3 livelli (aule -> core -> perimetro).",
    "",
    "1) Crea 4 switch totali:",
    "- 1 switch CORE centrale",
    "- 3 switch AULA collegati al core",
    "",
    "2) Collega i client:",
    "- almeno 2 PC per ogni switch aula (quindi almeno 6 PC totali)",
    "",
    "3) Collega servizi e uscita:",
    "- server collegato al core",
    "- core -> firewall -> router -> Internet",
    "",
    "La prova finale testa PC -> server e PC -> Internet.",
  ].join("\n"),
  checks: [
    "Almeno 6 PC",
    "4 switch totali: 1 core + 3 aule collegate al core",
    "Ogni switch aula ha almeno 2 PC",
    "Server collegato al core",
    "Uscita completa: core -> firewall -> router -> Internet",
  ],
  hint: "Prima crea lo switch core. Poi collega 3 switch aula al core, aggiungi 2 PC per aula, e solo alla fine collega server e uscita WAN.",
  info: "Nella rete gerarchica scolastica il traffico locale converge sul core. Da li passa al server interno o esce verso WAN tramite firewall e router.",
  validate: validateSchool,
  pairs: () => schoolPairs(),
});
